"""JavaScript code for QA reports.

This module contains functions that generate JavaScript code
for interactive report features.
"""

from typing import List


def get_threshold_control_scripts() -> List[str]:
    """Generate JavaScript for interactive threshold controls.

    Returns a list of JavaScript lines for threshold adjustment and export.
    """
    lines = []

    # Threshold state management
    lines.append("// Threshold control state")
    lines.append("let currentThresholds = {};")
    lines.append("let originalThresholds = {};")
    lines.append("")

    # Initialize thresholds from DOM
    lines.append("function initThresholdControls() {")
    lines.append("  const sliders = document.querySelectorAll('.threshold-slider');")
    lines.append("  sliders.forEach(function(slider) {")
    lines.append("    const key = slider.dataset.thresholdKey;")
    lines.append("    const value = parseFloat(slider.value);")
    lines.append("    currentThresholds[key] = value;")
    lines.append("    originalThresholds[key] = value;")
    lines.append("    ")
    lines.append("    // Sync slider and number input")
    lines.append("    const numberInput = document.getElementById(slider.id + '-value');")
    lines.append("    ")
    lines.append("    slider.addEventListener('input', function() {")
    lines.append("      const newValue = parseFloat(this.value);")
    lines.append("      numberInput.value = newValue;")
    lines.append("      updateThreshold(key, newValue);")
    lines.append("    });")
    lines.append("    ")
    lines.append("    numberInput.addEventListener('input', function() {")
    lines.append("      const newValue = parseFloat(this.value);")
    lines.append("      if (!isNaN(newValue)) {")
    lines.append("        slider.value = newValue;")
    lines.append("        updateThreshold(key, newValue);")
    lines.append("      }")
    lines.append("    });")
    lines.append("  });")
    lines.append("  ")
    lines.append("  // Reset button")
    lines.append("  const resetBtn = document.getElementById('reset-thresholds-btn');")
    lines.append("  if (resetBtn) {")
    lines.append("    resetBtn.addEventListener('click', resetThresholds);")
    lines.append("  }")
    lines.append("  ")
    lines.append("  // Export button")
    lines.append("  const exportBtn = document.getElementById('export-exclusions-btn');")
    lines.append("  if (exportBtn) {")
    lines.append("    exportBtn.addEventListener('click', exportExclusionList);")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # Update threshold and recalculate flags
    lines.append("function updateThreshold(key, value) {")
    lines.append("  currentThresholds[key] = value;")
    lines.append("  recalculateFlags();")
    lines.append("}")
    lines.append("")

    # FLAG_RULES mapping - mirrors Python flagging logic
    lines.append("const FLAG_RULES = {")
    lines.append("  'tsnr_low': {metric: 'tsnr_median', operator: '<', staticValue: 25},")
    lines.append("  'dvars_high': {metric: 'dvars_percent_above', operator: '>', staticValue: 15.0},")
    lines.append("  'outliers_high': {metric: 'outlier_percent_above', operator: '>', staticValue: 10.0},")
    lines.append("  'motion_high': {")
    lines.append("    composite: true,")
    lines.append("    conditions: [")
    lines.append("      {metric: 'fd_percent_above', operator: '>', staticValue: 20.0},")
    lines.append("      {metric: 'fd_median', operator: '>', thresholdKey: 'fd_median_threshold'}")
    lines.append("    ],")
    lines.append("    logic: 'OR'")
    lines.append("  },")
    lines.append("  'hyperintense_slices': {metric: 'n_hyperintense_slices', operator: '>', staticValue: 3},")
    lines.append("  'slice_outliers': {metric: 'slice_outlier_max', operator: '>', staticValue: 0.25},")
    lines.append("  'mask_fragmented': {metric: 'mask_components', operator: '>', staticValue: 3},")
    lines.append("  'physiological_noise_high': {metric: 'physiological_power_ratio', operator: '>', staticValue: 0.5}")
    lines.append("};")
    lines.append("")

    lines.append("function evaluateCondition(metricValue, operator, thresholdValue) {")
    lines.append("  if (metricValue === null || metricValue === undefined) return false;")
    lines.append("  switch(operator) {")
    lines.append("    case '>': return metricValue > thresholdValue;")
    lines.append("    case '<': return metricValue < thresholdValue;")
    lines.append("    case '>=': return metricValue >= thresholdValue;")
    lines.append("    case '<=': return metricValue <= thresholdValue;")
    lines.append("    case '==': return metricValue === thresholdValue;")
    lines.append("    default: return false;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    lines.append("function calculateRunFlags(runThresholdMetrics, currentThresholds) {")
    lines.append("  const flags = {};")
    lines.append("  for (const flagName in FLAG_RULES) {")
    lines.append("    const rule = FLAG_RULES[flagName];")
    lines.append("    if (rule.composite) {")
    lines.append("      const results = rule.conditions.map(cond => {")
    lines.append("        const thresholdValue = cond.thresholdKey ? currentThresholds[cond.thresholdKey] : cond.staticValue;")
    lines.append("        const metricValue = runThresholdMetrics[cond.metric];")
    lines.append("        return evaluateCondition(metricValue, cond.operator, thresholdValue);")
    lines.append("      });")
    lines.append("      flags[flagName] = rule.logic === 'OR' ? results.some(r => r) : results.every(r => r);")
    lines.append("    } else {")
    lines.append("      const thresholdValue = rule.thresholdKey ? currentThresholds[rule.thresholdKey] : rule.staticValue;")
    lines.append("      const metricValue = runThresholdMetrics[rule.metric];")
    lines.append("      flags[flagName] = evaluateCondition(metricValue, rule.operator, thresholdValue);")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return flags;")
    lines.append("}")
    lines.append("")

    # Recalculate flags based on new thresholds
    lines.append("function recalculateFlags() {")
    lines.append("  const exportDataEl = document.getElementById('qa-export-data');")
    lines.append("  if (!exportDataEl) return;")
    lines.append("  const data = JSON.parse(exportDataEl.textContent);")
    lines.append("  if (!data || !data.sessions) return;")
    lines.append("  ")
    lines.append("  let totalRuns = 0;")
    lines.append("  let totalFlagged = 0;")
    lines.append("  ")
    lines.append("  data.sessions.forEach(session => {")
    lines.append("    let sessionFlagged = 0;")
    lines.append("    session.runs.forEach(run => {")
    lines.append("      if (!run.threshold_metrics) return;")
    lines.append("      totalRuns++;")
    lines.append("      const newFlags = calculateRunFlags(run.threshold_metrics, currentThresholds);")
    lines.append("      run.flags = newFlags;")
    lines.append("      const flagCount = Object.values(newFlags).filter(Boolean).length;")
    lines.append("      if (flagCount > 0) {")
    lines.append("        totalFlagged++;")
    lines.append("        sessionFlagged++;")
    lines.append("      }")
    lines.append("    });")
    lines.append("  });")
    lines.append("  ")
    lines.append("  // Update export button")
    lines.append("  const hasChanges = Object.keys(currentThresholds).some(key => {")
    lines.append("    return Math.abs(currentThresholds[key] - originalThresholds[key]) > 0.001;")
    lines.append("  });")
    lines.append("  const exportBtn = document.getElementById('export-exclusions-btn');")
    lines.append("  if (exportBtn) {")
    lines.append("    exportBtn.textContent = hasChanges ? 'Export Updated Exclusion List (Modified)' : 'Export Exclusion List';")
    lines.append("    exportBtn.style.fontWeight = hasChanges ? 'bold' : '500';")
    lines.append("  }")
    lines.append("  ")
    lines.append("  console.log('Recalculated flags: ' + totalFlagged + '/' + totalRuns + ' flagged');")
    lines.append("}")
    lines.append("")

    # Reset thresholds
    lines.append("function resetThresholds() {")
    lines.append("  Object.keys(originalThresholds).forEach(key => {")
    lines.append("    const value = originalThresholds[key];")
    lines.append("    currentThresholds[key] = value;")
    lines.append("    ")
    lines.append("    const slider = document.getElementById('threshold-' + key);")
    lines.append("    const numberInput = document.getElementById('threshold-' + key + '-value');")
    lines.append("    ")
    lines.append("    if (slider) slider.value = value;")
    lines.append("    if (numberInput) numberInput.value = value;")
    lines.append("  });")
    lines.append("  ")
    lines.append("  recalculateFlags();")
    lines.append("}")
    lines.append("")

    # Export exclusion list
    lines.append("function exportExclusionList() {")
    lines.append("  // Build exclusion list based on current thresholds")
    lines.append("  const exclusionData = {")
    lines.append("    timestamp: new Date().toISOString(),")
    lines.append("    thresholds: currentThresholds,")
    lines.append("    exclusions: [],")
    lines.append("    note: 'Generated with modified thresholds via QA report interactive controls'")
    lines.append("  };")
    lines.append("  ")
    lines.append("  // TODO: In production, this would analyze actual run metrics against new thresholds")
    lines.append("  // For now, provide the thresholds configuration")
    lines.append("  ")
    lines.append("  const blob = new Blob([JSON.stringify(exclusionData, null, 2)], { type: 'application/json' });")
    lines.append("  const url = URL.createObjectURL(blob);")
    lines.append("  const a = document.createElement('a');")
    lines.append("  a.href = url;")
    lines.append("  a.download = 'exclusion_thresholds_' + new Date().toISOString().split('T')[0] + '.json';")
    lines.append("  document.body.appendChild(a);")
    lines.append("  a.click();")
    lines.append("  document.body.removeChild(a);")
    lines.append("  URL.revokeObjectURL(url);")
    lines.append("}")
    lines.append("")

    return lines


def get_subject_report_scripts() -> List[str]:
    """Generate JavaScript for subject reports.

    Returns a list of lines to be appended to the HTML.
    """
    lines = []
    lines.append("<script>")

    # Sidebar toggle
    lines.append("function toggleSidebar() {")
    lines.append("  const sidebar = document.getElementById('sidebar');")
    lines.append("  const overlay = document.querySelector('.sidebar-overlay');")
    lines.append("  sidebar.classList.toggle('open');")
    lines.append("  overlay.classList.toggle('active');")
    lines.append("}")
    lines.append("")

    # Quality state management
    lines.append("function getStorageKey(id) {")
    lines.append("  return 'qa_quality_' + id;")
    lines.append("}")
    lines.append("")
    lines.append("function loadQualityState(id) {")
    lines.append("  const key = getStorageKey(id);")
    lines.append("  const stored = localStorage.getItem(key);")
    lines.append("  return stored === 'good' ? 'good' : (stored === 'bad' ? 'bad' : null);")
    lines.append("}")
    lines.append("")
    lines.append("function saveQualityState(id, quality) {")
    lines.append("  const key = getStorageKey(id);")
    lines.append("  localStorage.setItem(key, quality);")
    lines.append("}")
    lines.append("")
    lines.append("function setQualityIndicator(element, quality) {")
    lines.append("  if (quality === 'good') {")
    lines.append("    element.className = 'quality-indicator quality-good';")
    lines.append("    element.textContent = '✓ Good';")
    lines.append("  } else {")
    lines.append("    element.className = 'quality-indicator quality-bad';")
    lines.append("    element.textContent = '✗ Bad';")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # Quality handlers
    lines.append("function handleRunQuality(runId, sessionId, event) {")
    lines.append("  event.stopPropagation();")
    lines.append("  const indicator = document.getElementById('run-' + runId);")
    lines.append("  const currentQuality = indicator.classList.contains('quality-good') ? 'good' : 'bad';")
    lines.append("  const newQuality = currentQuality === 'good' ? 'bad' : 'good';")
    lines.append("  setQualityIndicator(indicator, newQuality);")
    lines.append("  saveQualityState(runId, newQuality);")
    lines.append("  updateSessionQuality(sessionId);")
    lines.append("  updateReviewProgress();")
    lines.append("}")
    lines.append("")
    lines.append("function handleSessionQuality(sessionId, event) {")
    lines.append("  event.stopPropagation();")
    lines.append("  const indicator = document.getElementById('session-' + sessionId);")
    lines.append("  const currentQuality = indicator.classList.contains('quality-good') ? 'good' : 'bad';")
    lines.append("  const newQuality = currentQuality === 'good' ? 'bad' : 'good';")
    lines.append("  setQualityIndicator(indicator, newQuality);")
    lines.append("  saveQualityState(sessionId, newQuality);")
    lines.append("  const runIndicators = document.querySelectorAll('.quality-indicator[id^=\"run-\"][data-session-id=\"' + sessionId + '\"]');")
    lines.append("  runIndicators.forEach(function(runIndicator) {")
    lines.append("    const runId = runIndicator.id.replace('run-', '');")
    lines.append("    setQualityIndicator(runIndicator, newQuality);")
    lines.append("    saveQualityState(runId, newQuality);")
    lines.append("  });")
    lines.append("  updateReviewProgress();")
    lines.append("}")
    lines.append("")
    lines.append("function updateSessionQuality(sessionId) {")
    lines.append("  const sessionIndicator = document.getElementById('session-' + sessionId);")
    lines.append("  if (!sessionIndicator) return;")
    lines.append("  const runIndicators = document.querySelectorAll('.quality-indicator[id^=\"run-\"][data-session-id=\"' + sessionId + '\"]');")
    lines.append("  if (runIndicators.length === 0) return;")
    lines.append("  const allGood = Array.from(runIndicators).every(function(ind) { return ind.classList.contains('quality-good'); });")
    lines.append("  const allBad = Array.from(runIndicators).every(function(ind) { return ind.classList.contains('quality-bad'); });")
    lines.append("  if (allGood) {")
    lines.append("    setQualityIndicator(sessionIndicator, 'good');")
    lines.append("    saveQualityState(sessionId, 'good');")
    lines.append("  } else if (allBad) {")
    lines.append("    setQualityIndicator(sessionIndicator, 'bad');")
    lines.append("    saveQualityState(sessionId, 'bad');")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # Konami code easter egg
    lines.append("let konamiCode = [];")
    lines.append("const konamiSequence = ['ArrowUp', 'ArrowUp', 'ArrowDown', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'ArrowLeft', 'ArrowRight', 'KeyB', 'KeyA'];")
    lines.append("")

    # Dark mode
    lines.append("function toggleDarkMode() {")
    lines.append("  document.body.classList.toggle('dark-mode');")
    lines.append("  const isDark = document.body.classList.contains('dark-mode');")
    lines.append("  localStorage.setItem('qa_dark_mode', isDark);")
    lines.append("  document.querySelector('.dark-mode-toggle').textContent = isDark ? '☀️ Light' : '🌙 Dark';")
    lines.append("}")
    lines.append("")

    # Search/filter
    lines.append("function filterRuns() {")
    lines.append("  const searchTerm = document.getElementById('searchInput').value.toLowerCase();")
    lines.append("  const allDetails = document.querySelectorAll('details');")
    lines.append("  allDetails.forEach(function(detail) {")
    lines.append("    const text = detail.textContent.toLowerCase();")
    lines.append("    if (text.includes(searchTerm)) {")
    lines.append("      detail.classList.remove('hidden');")
    lines.append("    } else {")
    lines.append("      detail.classList.add('hidden');")
    lines.append("    }")
    lines.append("  });")
    lines.append("}")
    lines.append("")

    # Export modal
    lines.append("function openExportModal() {")
    lines.append("  document.getElementById('exportModal').classList.add('active');")
    lines.append("  document.getElementById('exportOverlay').classList.add('active');")
    lines.append("}")
    lines.append("")
    lines.append("function closeExportModal() {")
    lines.append("  document.getElementById('exportModal').classList.remove('active');")
    lines.append("  document.getElementById('exportOverlay').classList.remove('active');")
    lines.append("}")
    lines.append("")

    # Download helper
    lines.append("function downloadFile(content, filename, type) {")
    lines.append("  const blob = new Blob([content], { type: type });")
    lines.append("  const url = window.URL.createObjectURL(blob);")
    lines.append("  const a = document.createElement('a');")
    lines.append("  a.href = url;")
    lines.append("  a.download = filename;")
    lines.append("  document.body.appendChild(a);")
    lines.append("  a.click();")
    lines.append("  document.body.removeChild(a);")
    lines.append("  window.URL.revokeObjectURL(url);")
    lines.append("  closeExportModal();")
    lines.append("}")
    lines.append("")

    # Data access
    lines.append("function getQAData() {")
    lines.append("  const dataEl = document.getElementById('qa-export-data');")
    lines.append("  return dataEl ? JSON.parse(dataEl.textContent) : null;")
    lines.append("}")
    lines.append("")

    # Export functions
    lines.append("function exportJSON() {")
    lines.append("  const data = getQAData();")
    lines.append("  if (!data) { alert('No data available'); return; }")
    lines.append("  const json = JSON.stringify(data, null, 2);")
    lines.append("  const filename = 'qa_' + data.subject + '_' + new Date().toISOString().split('T')[0] + '.json';")
    lines.append("  downloadFile(json, filename, 'application/json');")
    lines.append("}")
    lines.append("")
    lines.append("function exportCSV() {")
    lines.append("  const data = getQAData();")
    lines.append("  if (!data) { alert('No data available'); return; }")
    lines.append("  const rows = [];")
    lines.append("  const metricKeys = new Set();")
    lines.append("  const flagKeys = new Set();")
    lines.append("  data.sessions.forEach(function(sess) {")
    lines.append("    sess.runs.forEach(function(run) {")
    lines.append("      Object.keys(run.metrics).forEach(function(k) { metricKeys.add(k); });")
    lines.append("      Object.keys(run.flags).forEach(function(k) { flagKeys.add(k); });")
    lines.append("    });")
    lines.append("  });")
    lines.append("  const metricList = Array.from(metricKeys).sort();")
    lines.append("  const flagList = Array.from(flagKeys).sort();")
    lines.append("  const header = ['subject', 'session', 'run', 'task', 'echo'].concat(metricList).concat(flagList.map(function(f) { return 'flag_' + f; }));")
    lines.append("  rows.push(header);")
    lines.append("  data.sessions.forEach(function(sess) {")
    lines.append("    sess.runs.forEach(function(run) {")
    lines.append("      const row = [data.subject, sess.session, run.run, run.task || '', run.echo || ''];")
    lines.append("      metricList.forEach(function(k) { row.push(run.metrics[k] !== undefined ? run.metrics[k] : ''); });")
    lines.append("      flagList.forEach(function(k) { row.push(run.flags[k] !== undefined ? (run.flags[k] ? 1 : 0) : ''); });")
    lines.append("      rows.push(row);")
    lines.append("    });")
    lines.append("  });")
    lines.append("  const csv = rows.map(function(row) { return row.map(function(cell) { return '\"' + String(cell).replace(/\"/g, '\"\"') + '\"'; }).join(','); }).join('\\n');")
    lines.append("  const filename = 'qa_' + data.subject + '_' + new Date().toISOString().split('T')[0] + '.csv';")
    lines.append("  downloadFile(csv, filename, 'text/csv');")
    lines.append("}")
    lines.append("")
    lines.append("function exportFlagged() {")
    lines.append("  const data = getQAData();")
    lines.append("  if (!data) { alert('No data available'); return; }")
    lines.append("  const rows = [];")
    lines.append("  rows.push(['subject', 'session', 'run', 'task', 'echo', 'flags', 'flag_count']);")
    lines.append("  data.sessions.forEach(function(sess) {")
    lines.append("    sess.runs.forEach(function(run) {")
    lines.append("      const activeFlags = Object.entries(run.flags).filter(function(e) { return e[1]; }).map(function(e) { return e[0]; });")
    lines.append("      if (activeFlags.length > 0) {")
    lines.append("        rows.push([data.subject, sess.session, run.run, run.task || '', run.echo || '', activeFlags.join('; '), activeFlags.length]);")
    lines.append("      }")
    lines.append("    });")
    lines.append("  });")
    lines.append("  if (rows.length === 1) { alert('No flagged runs found!'); closeExportModal(); return; }")
    lines.append("  const csv = rows.map(function(row) { return row.map(function(cell) { return '\"' + String(cell).replace(/\"/g, '\"\"') + '\"'; }).join(','); }).join('\\n');")
    lines.append("  const filename = 'qa_' + data.subject + '_flagged_' + new Date().toISOString().split('T')[0] + '.csv';")
    lines.append("  downloadFile(csv, filename, 'text/csv');")
    lines.append("}")
    lines.append("")

    # Easter egg
    lines.append("function closeEasterEgg() {")
    lines.append("  document.getElementById('easterEgg').classList.remove('active');")
    lines.append("}")
    lines.append("")
    lines.append("function checkKonamiCode(key) {")
    lines.append("  konamiCode.push(key);")
    lines.append("  if (konamiCode.length > konamiSequence.length) {")
    lines.append("    konamiCode.shift();")
    lines.append("  }")
    lines.append("  if (konamiCode.length === konamiSequence.length) {")
    lines.append("    let match = true;")
    lines.append("    for (let i = 0; i < konamiSequence.length; i++) {")
    lines.append("      if (konamiCode[i] !== konamiSequence[i]) {")
    lines.append("        match = false;")
    lines.append("        break;")
    lines.append("      }")
    lines.append("    }")
    lines.append("    if (match) {")
    lines.append("      document.getElementById('easterEgg').classList.add('active');")
    lines.append("      konamiCode = [];")
    lines.append("    }")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    # Keyboard navigation
    lines.append("let currentRunIndex = -1;")
    lines.append("let allRuns = [];")
    lines.append("")
    lines.append("function initKeyboardNavigation() {")
    lines.append("  // Only select run details, not session details")
    lines.append("  allRuns = Array.from(document.querySelectorAll('details[id^=\"run-details-\"]'));")
    lines.append("}")
    lines.append("")
    lines.append("function navigateRuns(direction) {")
    lines.append("  if (allRuns.length === 0) initKeyboardNavigation();")
    lines.append("  if (allRuns.length === 0) return;")
    lines.append("  if (currentRunIndex < 0) currentRunIndex = direction > 0 ? 0 : allRuns.length - 1;")
    lines.append("  else currentRunIndex += direction;")
    lines.append("  if (currentRunIndex < 0) currentRunIndex = allRuns.length - 1;")
    lines.append("  if (currentRunIndex >= allRuns.length) currentRunIndex = 0;")
    lines.append("  const runDetail = allRuns[currentRunIndex];")
    lines.append("  // Open parent session first")
    lines.append("  const parentSession = runDetail.closest('details[id^=\"session-details-\"]');")
    lines.append("  if (parentSession) parentSession.open = true;")
    lines.append("  runDetail.open = true;")
    lines.append("  runDetail.scrollIntoView({ behavior: 'smooth', block: 'start' });")
    lines.append("  // Update nav highlight")
    lines.append("  const runId = runDetail.id.replace('run-details-', '');")
    lines.append("  updateActiveNavItem(runId);")
    lines.append("}")
    lines.append("")

    # Keyboard event handler
    lines.append("document.addEventListener('keydown', function(e) {")
    lines.append("  if (e.target.tagName === 'INPUT') return;")
    lines.append("  if (e.key === 'j' || e.key === 'J') {")
    lines.append("    e.preventDefault();")
    lines.append("    navigateRuns(1);")
    lines.append("  } else if (e.key === 'k' || e.key === 'K') {")
    lines.append("    e.preventDefault();")
    lines.append("    navigateRuns(-1);")
    lines.append("  } else if (e.key === ' ' && e.target.tagName !== 'INPUT') {")
    lines.append("    e.preventDefault();")
    lines.append("    const focused = document.activeElement;")
    lines.append("    if (focused && focused.tagName === 'SUMMARY') {")
    lines.append("      focused.parentElement.open = !focused.parentElement.open;")
    lines.append("    }")
    lines.append("  } else if (e.key === '/' && e.target.tagName !== 'INPUT') {")
    lines.append("    e.preventDefault();")
    lines.append("    document.getElementById('searchInput').focus();")
    lines.append("  } else if (e.key === 'f' || e.key === 'F') {")
    lines.append("    e.preventDefault();")
    lines.append("    nextFlagged();")
    lines.append("  } else if (e.key === 'e' || e.key === 'E') {")
    lines.append("    e.preventDefault();")
    lines.append("    expandAll();")
    lines.append("  } else if (e.key === 'c' || e.key === 'C') {")
    lines.append("    e.preventDefault();")
    lines.append("    collapseAll();")
    lines.append("  }")
    lines.append("  checkKonamiCode(e.code);")
    lines.append("});")
    lines.append("")

    # Nav panel functions
    lines.append("function toggleNavPanel() {")
    lines.append("  document.getElementById('navPanel').classList.toggle('collapsed');")
    lines.append("  document.querySelector('.content-with-nav').classList.toggle('content-with-nav');")
    lines.append("}")
    lines.append("")
    lines.append("function navigateToRun(runId) {")
    lines.append("  const detail = document.getElementById('run-details-' + runId);")
    lines.append("  if (detail) {")
    lines.append("    // Open parent session first")
    lines.append("    const parent = detail.closest('details[id^=\"session-details-\"]');")
    lines.append("    if (parent) parent.open = true;")
    lines.append("    detail.open = true;")
    lines.append("    detail.scrollIntoView({ behavior: 'smooth', block: 'start' });")
    lines.append("    updateActiveNavItem(runId);")
    lines.append("    // Sync keyboard navigation index")
    lines.append("    if (allRuns.length === 0) initKeyboardNavigation();")
    lines.append("    currentRunIndex = allRuns.indexOf(detail);")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("function updateActiveNavItem(runId) {")
    lines.append("  document.querySelectorAll('.nav-item').forEach(function(item) {")
    lines.append("    item.classList.remove('active');")
    lines.append("  });")
    lines.append("  const navItem = document.querySelector('.nav-run[data-run=\"' + runId + '\"]');")
    lines.append("  if (navItem) {")
    lines.append("    navItem.classList.add('active');")
    lines.append("    // Scroll nav item into view within the nav panel")
    lines.append("    navItem.scrollIntoView({ behavior: 'smooth', block: 'nearest' });")
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("function filterNav(filter) {")
    lines.append("  document.querySelectorAll('.nav-filter-btn').forEach(function(btn) { btn.classList.remove('active'); });")
    lines.append("  document.getElementById('filter' + filter.charAt(0).toUpperCase() + filter.slice(1)).classList.add('active');")
    lines.append("  const navRuns = document.querySelectorAll('.nav-run');")
    lines.append("  navRuns.forEach(function(item) {")
    lines.append("    if (filter === 'all') {")
    lines.append("      item.style.display = '';")
    lines.append("    } else if (filter === 'flagged') {")
    lines.append("      item.style.display = item.dataset.flagged === 'true' ? '' : 'none';")
    lines.append("    }")
    lines.append("  });")
    lines.append("}")
    lines.append("")
    lines.append("function updateReviewProgress() {")
    lines.append("  const total = document.querySelectorAll('.nav-run').length;")
    lines.append("  let reviewed = 0;")
    lines.append("  document.querySelectorAll('.nav-run').forEach(function(item) {")
    lines.append("    const runId = item.dataset.run;")
    lines.append("    if (loadQualityState(runId)) reviewed++;")
    lines.append("  });")
    lines.append("  document.getElementById('reviewCount').textContent = reviewed;")
    lines.append("  const pct = total > 0 ? (reviewed / total * 100) : 0;")
    lines.append("  document.getElementById('progressFill').style.width = pct + '%';")
    lines.append("  // Update nav item dots based on quality state")
    lines.append("  document.querySelectorAll('.nav-run').forEach(function(item) {")
    lines.append("    const runId = item.dataset.run;")
    lines.append("    const quality = loadQualityState(runId);")
    lines.append("    const dot = item.querySelector('.nav-item-dot');")
    lines.append("    if (quality === 'good') {")
    lines.append("      dot.classList.remove('flagged', 'bad');")
    lines.append("      dot.classList.add('good');")
    lines.append("    } else if (quality === 'bad') {")
    lines.append("      dot.classList.remove('flagged', 'good');")
    lines.append("      dot.classList.add('bad');")
    lines.append("    }")
    lines.append("  });")
    lines.append("}")
    lines.append("")

    # Expand/collapse helpers
    lines.append("function expandAll() {")
    lines.append("  document.querySelectorAll('details').forEach(function(d) { d.open = true; });")
    lines.append("}")
    lines.append("function collapseAll() {")
    lines.append("  document.querySelectorAll('details').forEach(function(d) { d.open = false; });")
    lines.append("}")
    lines.append("function nextFlagged() {")
    lines.append("  const flaggedRuns = document.querySelectorAll('.nav-run[data-flagged=\"true\"]');")
    lines.append("  if (flaggedRuns.length === 0) return;")
    lines.append("  const activeRun = document.querySelector('.nav-run.active');")
    lines.append("  let nextIndex = 0;")
    lines.append("  if (activeRun) {")
    lines.append("    for (let i = 0; i < flaggedRuns.length; i++) {")
    lines.append("      if (flaggedRuns[i] === activeRun) { nextIndex = (i + 1) % flaggedRuns.length; break; }")
    lines.append("    }")
    lines.append("  }")
    lines.append("  navigateToRun(flaggedRuns[nextIndex].dataset.run);")
    lines.append("}")
    lines.append("")

    # Thumbnail density toggle
    lines.append("function setThumbDensity(density, button) {")
    lines.append("  const grids = document.querySelectorAll('.thumb-grid');")
    lines.append("  const buttons = document.querySelectorAll('.density-btn');")
    lines.append("  buttons.forEach(function(btn) { btn.classList.remove('active'); });")
    lines.append("  button.classList.add('active');")
    lines.append("  grids.forEach(function(grid) {")
    lines.append("    grid.classList.remove('density-compact', 'density-spacious');")
    lines.append("    if (density === 'compact') grid.classList.add('density-compact');")
    lines.append("    if (density === 'spacious') grid.classList.add('density-spacious');")
    lines.append("  });")
    lines.append("  localStorage.setItem('qa_thumb_density', density);")
    lines.append("}")
    lines.append("")

    # Add threshold control functions
    lines.extend(get_threshold_control_scripts())

    # DOMContentLoaded handler
    lines.append("document.addEventListener('DOMContentLoaded', function() {")
    lines.append("  const darkMode = localStorage.getItem('qa_dark_mode') === 'true';")
    lines.append("  if (darkMode) {")
    lines.append("    document.body.classList.add('dark-mode');")
    lines.append("    document.querySelector('.dark-mode-toggle').textContent = '☀️ Light';")
    lines.append("  }")
    lines.append("  const allIndicators = document.querySelectorAll('.quality-indicator[id^=\"run-\"], .quality-indicator[id^=\"session-\"]');")
    lines.append("  allIndicators.forEach(function(indicator) {")
    lines.append("    const id = indicator.id.replace(/^(run-|session-)/, '');")
    lines.append("    const storedQuality = loadQualityState(id);")
    lines.append("    if (storedQuality) {")
    lines.append("      setQualityIndicator(indicator, storedQuality);")
    lines.append("    }")
    lines.append("  });")
    lines.append("  const sessionIndicators = document.querySelectorAll('.quality-indicator[id^=\"session-\"]');")
    lines.append("  sessionIndicators.forEach(function(sessionIndicator) {")
    lines.append("    const sessionId = sessionIndicator.id.replace('session-', '');")
    lines.append("    updateSessionQuality(sessionId);")
    lines.append("  });")
    lines.append("  initKeyboardNavigation();")
    lines.append("  updateReviewProgress();")
    lines.append("  initTooltips();")
    lines.append("  initThresholdControls();")
    lines.append("  ")
    lines.append("  // Restore saved thumbnail density")
    lines.append("  const savedDensity = localStorage.getItem('qa_thumb_density');")
    lines.append("  if (savedDensity) {")
    lines.append("    const densityBtns = document.querySelectorAll('.density-btn');")
    lines.append("    densityBtns.forEach(function(btn) {")
    lines.append("      if (btn.textContent.toLowerCase() === savedDensity) {")
    lines.append("        btn.classList.add('active');")
    lines.append("        const grids = document.querySelectorAll('.thumb-grid');")
    lines.append("        grids.forEach(function(grid) {")
    lines.append("          if (savedDensity === 'compact') grid.classList.add('density-compact');")
    lines.append("          if (savedDensity === 'spacious') grid.classList.add('density-spacious');")
    lines.append("        });")
    lines.append("      } else {")
    lines.append("        btn.classList.remove('active');")
    lines.append("      }")
    lines.append("    });")
    lines.append("  }")
    lines.append("});")
    lines.append("")

    # Tooltip positioning
    lines.append("function initTooltips() {")
    lines.append("  document.querySelectorAll('.metric-name').forEach(function(el) {")
    lines.append("    const tooltip = el.querySelector('.tooltip-text');")
    lines.append("    if (!tooltip) return;")
    lines.append("    el.addEventListener('mouseenter', function(e) {")
    lines.append("      const rect = el.getBoundingClientRect();")
    lines.append("      const tooltipWidth = 300;")
    lines.append("      let left = rect.left;")
    lines.append("      let top = rect.bottom + 8;")
    lines.append("      if (left + tooltipWidth > window.innerWidth - 16) {")
    lines.append("        left = window.innerWidth - tooltipWidth - 16;")
    lines.append("      }")
    lines.append("      if (top + 100 > window.innerHeight) {")
    lines.append("        top = rect.top - 8;")
    lines.append("        tooltip.style.transform = 'translateY(-100%)';")
    lines.append("      } else {")
    lines.append("        tooltip.style.transform = 'translateY(0)';")
    lines.append("      }")
    lines.append("      tooltip.style.left = left + 'px';")
    lines.append("      tooltip.style.top = top + 'px';")
    lines.append("    });")
    lines.append("  });")
    lines.append("}")

    lines.append("</script>")
    return lines


def get_study_report_scripts() -> List[str]:
    """Generate JavaScript for study reports.

    Returns a list of lines to be appended to the HTML.
    """
    lines = []
    lines.append("<script>")

    # Dark mode toggle
    lines.append("function toggleDarkMode() {")
    lines.append("  document.body.classList.toggle('dark-mode');")
    lines.append("  const isDark = document.body.classList.contains('dark-mode');")
    lines.append("  localStorage.setItem('qa_dark_mode', isDark);")
    lines.append("  const btn = document.querySelector('.dark-mode-toggle');")
    lines.append("  if (btn) btn.textContent = isDark ? '☀️ Light' : '🌙 Dark';")
    lines.append("}")
    lines.append("")

    # Add threshold control functions
    lines.extend(get_threshold_control_scripts())

    # DOMContentLoaded for dark mode
    lines.append("document.addEventListener('DOMContentLoaded', function() {")
    lines.append("  const darkMode = localStorage.getItem('qa_dark_mode') === 'true';")
    lines.append("  if (darkMode) {")
    lines.append("    document.body.classList.add('dark-mode');")
    lines.append("    const btn = document.querySelector('.dark-mode-toggle');")
    lines.append("    if (btn) btn.textContent = '☀️ Light';")
    lines.append("  }")
    lines.append("  initTooltips();")
    lines.append("  initThresholdControls();")
    lines.append("});")
    lines.append("")

    # Tooltip positioning
    lines.append("function initTooltips() {")
    lines.append("  document.querySelectorAll('.metric-name').forEach(function(el) {")
    lines.append("    const tooltip = el.querySelector('.tooltip-text');")
    lines.append("    if (!tooltip) return;")
    lines.append("    el.addEventListener('mouseenter', function(e) {")
    lines.append("      const rect = el.getBoundingClientRect();")
    lines.append("      const tooltipWidth = 300;")
    lines.append("      let left = rect.left;")
    lines.append("      let top = rect.bottom + 8;")
    lines.append("      if (left + tooltipWidth > window.innerWidth - 16) {")
    lines.append("        left = window.innerWidth - tooltipWidth - 16;")
    lines.append("      }")
    lines.append("      if (top + 100 > window.innerHeight) {")
    lines.append("        top = rect.top - 8;")
    lines.append("        tooltip.style.transform = 'translateY(-100%)';")
    lines.append("      } else {")
    lines.append("        tooltip.style.transform = 'translateY(0)';")
    lines.append("      }")
    lines.append("      tooltip.style.left = left + 'px';")
    lines.append("      tooltip.style.top = top + 'px';")
    lines.append("    });")
    lines.append("  });")
    lines.append("}")

    lines.append("</script>")
    return lines
